# Apple-inspired dark green theme
[theme]
primaryColor = "#FEFEFF"                # Accent (dark)
backgroundColor = "#606C38"             # Deep olive green
secondaryBackgroundColor = "#FEFAE0"    # Dark brownish panel
textColor = "#000000"                   # Soft white text
font = "sans serif"
